### ISSUE TITLE
Rm administration#index exception

### ISSUE THREAD

**Issue by cthielen** [dssit/dss-wayfinding#91]
Here's the trace:

An ActiveRecord::RecordInvalid occurred in administration#index:

  Validation failed: Rm can't be blank
  lib/authentication.rb:114:in `authenticate'

-------------------------------
Request:
-------------------------------

  * URL        : https://wayfinding.dss.ucdavis.edu/administration?ticket=ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9
  * HTTP Method: GET
  * IP address : 168.150.24.31
  * Parameters : {"ticket"=>"ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9", "action"=>"index", "controller"=>"administration"}
  * Timestamp  : 2015-03-31 10:36:16 -0700
  * Server : roles.dss.ucdavis.edu
  * Rails root : /home/deployer/apps/dss-wayfinding/releases/20150123173644
  * Process: 26595

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: #<ActionDispatch::Request::Session:0x007f1f4c9f9710 ...>

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /home/deployer/apps/dss-wayfinding/current/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : DEVICE_SCREEN_WIDTH=2560; __uvt=; __qca=P0-1611204870-1423004499992; WT_FPC=id=b3051d79-5370-4dc9-8587-cfd5cfacca41:lv=1423004500100:ss=1423004500100; slowcon=0; CM_CURRENTSUBJECT=PED; CM_CURRENTCOURSE=201408%2D81419%2D635711; MYUCDAVIS_POLLS=1149%2C941%2C762%2C764; MYUCDAVIS_LANDING_IMAGE=bikesandtrees%2Ejpg%2Cblossoms%2Ejpg%2Cccinterior%2Ejpg%2Cegret%2Ejpg%2Ccpool%2Ejpg%2Cdeathblossom%2Ejpg; MYUCDAVIS_SMARTPOLL1=1155%2C941%2C762; __utma=224820510.1172787821.1418835308.1427753615.1427755635.17; __utmc=224820510; __utmz=224820510.1425056186.10.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); uvts=2XPxGImRwwdrVYW0; PORTALTHEME=standard%5F0%2C2; _gat=1; _ga=GA1.2.1172787821.1418835308; _dss-wayfinding_session=NEx3OGFYWU9UaDVYTi96MmhieWZla1ZKVEE1cDdGNWN5MkRJaHBFZ2tIazVWTmxnbWU0UFY5N1UxZkZFQkQzV09VenZhSytnMmt4ejJjTHQzRk1IaWNMeDd2OGdxcW1PNWY1VE45a0JPREdicFV2T3N5aEtSUjlTSmVSVyttSDBIWDkvWkE5WlZZNUwxREEyeUd!
 iMU1sRTg0
 cFFMSi9kaHdHSFRSLy8xdS9ISDFDNC9lZHRMeHBCdHUzU0VtZHJBbDgwM29YcjU0SE9INWNIdU5lYi9Nc0tWUzBRL3Q0MGZzOElNdk1YTmEvVHlBQ0h6cjEvczF2R1hxWmtpaVZMMS9ud1J3UFF3TWFRUHlodTNFL1A0OXhUY2JMcWQwamdlSS8zT3JWQmdvWFBqeXF2THpTMlErbFBWTGcxZEV6anpSZDBaNDFPemt4NXVVMGxqVHY4TmEvdnA3aDZOV015cXdFTkJEWm90Y1d2cVZwbjY2RWFpaWpUWWNYa0x6MEoyWDFQQlNYMm5lQnV5bTVsdExFaXV0QTdVbnJNRkhCOVZZZUJkWnp3eUo4QT0tLUNwY3FpM0tYQ1pDWTJ0SzgvRGcrTnc9PQ%3D%3D--cca54fcf557e31a6aae38a0966515fe221395263
  * HTTP_HOST                                      : wayfinding.dss.ucdavis.edu
  * HTTP_REFERER                                   : https://wayfinding.dss.ucdavis.edu/map
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
  * HTTP_X_FORWARDED_PROTO                         : https
  * ORIGINAL_FULLPATH                              : /administration?ticket=ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9
  * ORIGINAL_SCRIPT_NAME                           : 
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PATH_INFO                                      : /administration
  * QUERY_STRING                                   : ticket=ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9
  * REMOTE_ADDR                                    : 168.150.24.31
  * REMOTE_PORT                                    : 62615
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /administration?ticket=ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9
  * ROUTES_69886391418520_SCRIPT_NAME              : 
  * SCGI                                           : 1
  * SCRIPT_NAME                                    : 
  * SERVER_ADDR                                    : 169.237.120.176
  * SERVER_NAME                                    : wayfinding.dss.ucdavis.edu
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.6.2
  * action_controller.instance                     : #<AdministrationController:0x007f1f4c9f81a8>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007f1f60042c58>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f1f4d401438>
  * action_dispatch.cookies_serializer             : json
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007f1f600377b8>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x007f1f6307cc98>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 168.150.24.31
  * action_dispatch.request.content_type           : 
  * action_dispatch.request.flash_hash             : #<ActionDispatch::Flash::FlashHash:0x007f1f4ca686d8>
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f1f631ac140 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">]
  * action_dispatch.request.parameters             : {"ticket"=>"ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9", "action"=>"index", "controller"=>"administration"}
  * action_dispatch.request.path_parameters        : {:action=>"index", :controller=>"administration"}
  * action_dispatch.request.query_parameters       : {"ticket"=>"ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"da6f83db07bcf251e7b8d959d1ddec6f", "_csrf_token"=>"wN4gWBSooSsJx1Wzvhgs8BxXVh7TJUVxmoJ0hSoo9Rg=", "cas_sent_to_gateway"=>false, "cas_validation_retry_count"=>0, "previous_redirect_to_cas"=>"2015-03-31 10:36:16 -0700", "flash"=>{"discard"=>[], "flashes"=>{"error"=>"You must be logged in to access this section"}}}
  * action_dispatch.request_id                     : de0a0d19-b4ef-4e7e-b837-de7038169444
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x007f1f6311fd30>
  * action_dispatch.secret_key_base                : b82bdfd9d141e6990a861aef73b60b0e8c78efbd72abb098fe7b160c5720180cd222034c8c4a634175d06149f2c39948549b273fb90b24f413642e761facc68b
  * action_dispatch.secret_token                   : 
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x007f1f5f6e5c00>
  * rack.hijack                                    : #<Proc:0x007f1f4c9faf70@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f1f4c9fb150>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"DEVICE_SCREEN_WIDTH"=>"2560", "__uvt"=>"", "__qca"=>"P0-1611204870-1423004499992", "WT_FPC"=>"id=b3051d79-5370-4dc9-8587-cfd5cfacca41:lv=1423004500100:ss=1423004500100", "slowcon"=>"0", "CM_CURRENTSUBJECT"=>"PED", "CM_CURRENTCOURSE"=>"201408-81419-635711", "MYUCDAVIS_POLLS"=>"1149,941,762,764", "MYUCDAVIS_LANDING_IMAGE"=>"bikesandtrees.jpg,blossoms.jpg,ccinterior.jpg,egret.jpg,cpool.jpg,deathblossom.jpg", "MYUCDAVIS_SMARTPOLL1"=>"1155,941,762", "__utma"=>"224820510.1172787821.1418835308.1427753615.1427755635.17", "__utmc"=>"224820510", "__utmz"=>"224820510.1425056186.10.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)", "uvts"=>"2XPxGImRwwdrVYW0", "PORTALTHEME"=>"standard_0,2", "_gat"=>"1", "_ga"=>"GA1.2.1172787821.1418835308", "_dss-wayfinding_session"=>"NEx3OGFYWU9UaDVYTi96MmhieWZla1ZKVEE1cDdGNWN5MkRJaHBFZ2tIazVWTmxnbWU0UFY5N1UxZkZFQkQzV09VenZhSytnMmt4ejJjTHQzRk1IaWNMeDd2OGdxcW1PNWY1VE45a0JPREdicFV!
 2T3N5aEtS
 UjlTSmVSVyttSDBIWDkvWkE5WlZZNUwxREEyeUdiMU1sRTg0cFFMSi9kaHdHSFRSLy8xdS9ISDFDNC9lZHRMeHBCdHUzU0VtZHJBbDgwM29YcjU0SE9INWNIdU5lYi9Nc0tWUzBRL3Q0MGZzOElNdk1YTmEvVHlBQ0h6cjEvczF2R1hxWmtpaVZMMS9ud1J3UFF3TWFRUHlodTNFL1A0OXhUY2JMcWQwamdlSS8zT3JWQmdvWFBqeXF2THpTMlErbFBWTGcxZEV6anpSZDBaNDFPemt4NXVVMGxqVHY4TmEvdnA3aDZOV015cXdFTkJEWm90Y1d2cVZwbjY2RWFpaWpUWWNYa0x6MEoyWDFQQlNYMm5lQnV5bTVsdExFaXV0QTdVbnJNRkhCOVZZZUJkWnp3eUo4QT0tLUNwY3FpM0tYQ1pDWTJ0SzgvRGcrTnc9PQ==--cca54fcf557e31a6aae38a0966515fe221395263"}
  * rack.request.cookie_string                     : DEVICE_SCREEN_WIDTH=2560; __uvt=; __qca=P0-1611204870-1423004499992; WT_FPC=id=b3051d79-5370-4dc9-8587-cfd5cfacca41:lv=1423004500100:ss=1423004500100; slowcon=0; CM_CURRENTSUBJECT=PED; CM_CURRENTCOURSE=201408%2D81419%2D635711; MYUCDAVIS_POLLS=1149%2C941%2C762%2C764; MYUCDAVIS_LANDING_IMAGE=bikesandtrees%2Ejpg%2Cblossoms%2Ejpg%2Cccinterior%2Ejpg%2Cegret%2Ejpg%2Ccpool%2Ejpg%2Cdeathblossom%2Ejpg; MYUCDAVIS_SMARTPOLL1=1155%2C941%2C762; __utma=224820510.1172787821.1418835308.1427753615.1427755635.17; __utmc=224820510; __utmz=224820510.1425056186.10.4.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); uvts=2XPxGImRwwdrVYW0; PORTALTHEME=standard%5F0%2C2; _gat=1; _ga=GA1.2.1172787821.1418835308; _dss-wayfinding_session=NEx3OGFYWU9UaDVYTi96MmhieWZla1ZKVEE1cDdGNWN5MkRJaHBFZ2tIazVWTmxnbWU0UFY5N1UxZkZFQkQzV09VenZhSytnMmt4ejJjTHQzRk1IaWNMeDd2OGdxcW1PNWY1VE45a0JPREdicFV2T3N5aEtSUjlTSmVSVyttSDBIWDkvWkE5WlZZNUwxREEyeUd!
 iMU1sRTg0
 cFFMSi9kaHdHSFRSLy8xdS9ISDFDNC9lZHRMeHBCdHUzU0VtZHJBbDgwM29YcjU0SE9INWNIdU5lYi9Nc0tWUzBRL3Q0MGZzOElNdk1YTmEvVHlBQ0h6cjEvczF2R1hxWmtpaVZMMS9ud1J3UFF3TWFRUHlodTNFL1A0OXhUY2JMcWQwamdlSS8zT3JWQmdvWFBqeXF2THpTMlErbFBWTGcxZEV6anpSZDBaNDFPemt4NXVVMGxqVHY4TmEvdnA3aDZOV015cXdFTkJEWm90Y1d2cVZwbjY2RWFpaWpUWWNYa0x6MEoyWDFQQlNYMm5lQnV5bTVsdExFaXV0QTdVbnJNRkhCOVZZZUJkWnp3eUo4QT0tLUNwY3FpM0tYQ1pDWTJ0SzgvRGcrTnc9PQ%3D%3D--cca54fcf557e31a6aae38a0966515fe221395263
  * rack.request.query_hash                        : {"ticket"=>"ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9"}
  * rack.request.query_string                      : ticket=ST-522020-DHzUbovSEzdHV0dAFCIX-casweb9
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f1f4c9f9710>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f1f4c9f96c0>
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]

-------------------------------
Backtrace:
-------------------------------

  lib/authentication.rb:114:in `authenticate'

**Comment by cthielen** [comment]
Eric fixed this "somehow".
